resolver: nightly-2021-11-15
compiler: ghc-9.0.1

system-ghc: true
allow-newer: true

packages:
- .

extra-deps:
- git: https://github.com/wenkokke/sized-functors.git
  commit: bc16e547b199b9eb61df743fdb6de8f748f826a4
- git: https://github.com/wenkokke/testing-feat.git
  commit: a1b32842a8cc8ab467d93a9f97f2365330a02113
- git: https://github.com/wenkokke/lazy-search.git
  commit: c5f1d5db02ca9e07bbb73ef73860310d201ed15f
